name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v2

      - name: Fazer Upload dos arquivos
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."

      - name: Deploy
        uses: actions/deploy-pages@v2
